### ISSUE TITLE
解决

### ISSUE THREAD

**Issue by kebenxiaoming** [adamin1990/adamin1990.github.io#1]
1、参加活动的提交方法

api.php?g=Api&c=Activity&a=submit&q=1&id=活动id

还有些post参数，等再单独看一下

2、收货地址哪些还是用调用地址管理的地址列表就行，然后返回的时候get参数带一个adress_id

3、农场哪些还是和手机端原来一样的

**Comment by XPLeeAndroid** [comment]
@kebenxiaoming  WTF?
